<?xml version="1.0"?>
<package format="3">
  <name>ld_parser_cpp</name>
  <version>0.1.0</version>
  <description>Hệ thống tích hợp LD14 và MPU6050 qua ESP32</description>
  <maintainer email="datham221@gmail.com">naki</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>
  <depend>slam_toolbox</depend>
  <depend>imu_filter_madgwick</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>serial</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
