<?xml version="1.0"?>
<package format="3">
  <name>ld_slam_py</name>
  <version>0.1.0</version>
  <description>Package xử lý SLAM cho robot</description>
  <maintainer email="datham221@gmail.com">naki</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>slam_toolbox</depend>
  <depend>imu_filter_madgwick</depend>
  <depend>tf2_ros</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
